
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/69c471a82d2314db1a1c9095

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "q",
    "number": "1234-5"
}