# Variables ------------------------------------------------------
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImJlcmVuamVuYTIiLCJpZCI6IjY5ZGVmNjA4ZjlhMTFlODYzZmMzN2U5ZSIsImlhdCI6MTc3OTA0NzA0OH0.nE-eDGkMBUsfpA5lMS29UybY6P1_WLMXeAff-pMQ5Zc

@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6ImJlcmVuamVuYTIiLCJpZCI6IjY5ZGVmNjA4ZjlhMTFlODYzZmMzN2U5ZSIsImlhdCI6MTc3NjIyMzQxMn0.vT-kKQrsAr1OksgRG32nwlEKKVre_mdeDJm6k1GTt7o

@idDelete = 69def835f9a11e863fc37ead

@idBlog = 6a0d392aa985ed9434e896f5
#### ---------------------------------------------------------------

# Get All
GET http://localhost:3000/api/blogs

### GetId
GET http://localhost:3000/api/blogs/{{idBlog}}

### Post create
POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "50 sombras de los papoticos 4",
    "author": "papas",
    "url": "https://nosequrl",
    "likes": 5
}

### Delete

DELETE http://localhost:3000/api/blogs/{{idBlog}}
Authorization: Bearer {{token}}


### Update like
PATCH http://localhost:3000/api/blogs/{{idBlog}}/likes
Content-Type: application/json

{
"likes": 20
}

### update comments 
PATCH  http://localhost:3000/api/blogs/{{idBlog}}/comments
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "text": "!!Hello world!!"
}
